namespace: wordpress

wordpress:
  image: wordpress:5.5.1
  service:
    type: NodePort
    port: 80
    nodePort: 30692
  env:
    - name: WORDPRESS_DB_USER
      valueFrom:
        secretKeyRef:
          name: wordpress-secrets
          key: WORDPRESS_DB_USER
    - name: WORDPRESS_DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: wordpress-secrets
          key: WORDPRESS_DB_PASSWORD

mysql:
  image: mysql:8.0.27
  service:
    type: ClusterIP
    port: 3306
  env:
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: wordpress-secrets
          key: MYSQL_ROOT_PASSWORD
  persistence:
    enabled: true
    existingClaim: local-pvc

phpmyadmin:
  image: phpmyadmin/phpmyadmin
  service:
    type: NodePort
    port: 8080
    targetPort: 80

nfs:
  path: "/data"
  storage: 5Gi
