apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-entrypoint
  namespace: {{ .Values.namespace }}
data:
  docker-entrypoint.sh: |
    #!/bin/bash

    SECRET_FILE="/secrets/secrets.yaml"

    if [ -f "$SECRET_FILE" ]; then
        USERNAME=$(grep 'username:' "$SECRET_FILE" | awk '{print $2}')
        PASSWORD=$(grep 'password:' "$SECRET_FILE" | awk '{print $2}')
        export WORDPRESS_DB_USER=$USERNAME
        export WORDPRESS_DB_PASSWORD=$PASSWORD
    fi

    exec "$@"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-secrets
  namespace: wordpress
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
data:
  secrets.yaml: |
    username: c3Rhcw==
    password: ZGFuY2V0ZWFtNzQ3
