apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: {{ .Values.phpmyadmin.image }}
          ports:
            - containerPort: 80
          env:
            - name: PMA_HOST
              value: mysql
            - name: PMA_PORT
              value: "3306"
            - name: PMA_USER
              valueFrom:
                secretKeyRef:
                  name: wordpress-secrets
                  key: WORDPRESS_DB_USER
            - name: PMA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wordpress-secrets
                  key: WORDPRESS_DB_PASSWORD
            - name: PMA_ARBITRARY
              value: "1"
            - name: PMA_LANG
              value: en_US
          volumeMounts:
            - name: phpmyadmin-storage
              mountPath: /sessions
      volumes:
        - name: phpmyadmin-storage
          persistentVolumeClaim:
            claimName: local-pvc
