apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-pvc
  namespace: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ""
  volumeMode: Filesystem
