apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secrets
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
data:
  MYSQL_ROOT_PASSWORD: ZGFuY2V0ZWFtNzQ3  # Base64-encoded value of "danceteam747"
  WORDPRESS_DB_USER: c3Rhcw==            # Base64-encoded value of "stas"
  WORDPRESS_DB_PASSWORD: ZGFuY2V0ZWFtNzQ3  # Base64-encoded value of "danceteam747"
